# PHOX: Remote control gate opener.
#
# Characteristic
#  * Rolling code transmission
#  * 868.35 MHz version
#  * 4-button version
#
# Manufacturer: https://alutech-group.com/eu-en/homeowner/documentation/gate-automation/
# 
#   -X 'n=ALUTECH-AT-4N-868,m=OOK_PWN,s=320,l=740,r=4190,preamble=fff' -Y classic 
# 
# TODO:
#  * Basic identification 
#
decoder {
    name        = ALUTECH-AT-4N-868,
    modulation  = OOK_PWM,
    short	= 320,
    long	= 740,
    reset	= 4190,
    preamble= fff,
    sync	= 2596,
    bits	= 72,
    repeats    >= 2,
    unique,
    get          =@28:{4}:key:[7:A 11:B 13:C 14:D],
    get          =@36:{16}:code:%04x,
}
